name: CI-AMI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace Secrets
        run: |
          # Access the secret values

          
          cd packer/jenkins
          ls -al
          
          ADMIN_ID="${{ secrets.JENKINS_ADMIN_ID }}"
          ADMIN_PASSWORD="${{ secrets.JENKINS_ADMIN_PASSWORD }}"
          TOKEN="${{ secrets.TOKEN }}"
          USERNAME="${{ secrets.USERNAME }}"
          QUAY_ADMIN_ID="${{ secrets.QUAY_ADMIN_ID }}"
          QUAY_PASSWORD="${{ secrets.QUAY_PASSWORD }}"

          # # Replace secrets in the .docker.env file

          # sed -i ''  "s/\{{ secrets.JENKINS_ADMIN_ID }}/$JENKINS_ADMIN_ID/g" .docker.env
          # sed -i ''  "s/\{{ secrets.JENKINS_ADMIN_PASSWORD }}/$JENKINS_ADMIN_PASSWORD/g" .docker.env
          # sed -i ''  's/\{{ secrets.TOKEN }}'/$TOKEN/g .docker.env
          # sed -i ''  's/\{{ secrets.USERNAME }}'/$USERNAME/g .docker.env
          # sed -i ''  "s/\{{ secrets.QUAY_ADMIN_ID }}/$QUAY_ADMIN_ID/g" .docker.env
          # sed -i ''  "s/\{{ secrets.QUAY_PASSWORD }}/$QUAY_PASSWORD/g" .docker.env
        env:
            ADMIN_ID: ${{ secrets.JENKINS_ADMIN_ID }}
            ADMIN_PASSWORD: ${{ secrets.JENKINS_ADMIN_PASSWORD }}
            TOKEN: ${{ secrets.TOKEN }}
            USERNAME: ${{ secrets.USERNAME }}
            QUAY_ADMIN_ID: ${{ secrets.QUAY_ADMIN_ID }}
            QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}




      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/ami.pkr.hcl
        env:
          PACKER_LOG: 1
          PKR_VAR_public_key: ${{ secrets.PUBLIC_SSL_KEY }}
          PKR_VAR_private_key: ${{ secrets.PRIVATE_SSL_KEY }}
          ADMIN_ID: ${{ secrets.JENKINS_ADMIN_ID }}
          ADMIN_PASSWORD: ${{ secrets.JENKINS_ADMIN_PASSWORD }}
          KEY: ${{ secrets.KEY }}
          QUAY_ADMIN_ID: ${{ secrets.QUAY_ADMIN_ID }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  
