name: CI-AMI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/ami.pkr.hcl
        env:
          PACKER_LOG: 1
          PKR_VAR_public_key: ${{ secrets.PUBLIC_SSL_KEY }}
          PKR_VAR_private_key: ${{ secrets.PRIVATE_SSL_KEY }}

      - name: Build Artifact packer AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer/ami.pkr.hcl
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PKR_VAR_public_key: ${{ secrets.PUBLIC_SSL_KEY }}
          PKR_VAR_private_key: ${{ secrets.PRIVATE_SSL_KEY }}
